<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Главная</title>
        <link href="../../template/css/style.css" rel="stylesheet" type="text/css"/>
        <link href="../../template/css/blog.css" rel="stylesheet" type="text/css"/>
    </head>
    <body>
    <div class="block_10"> 
        <div class="block_13">
            <div class="block_11">
                <a href="/">
                    <img src="../../template/img/logo (1).png"/>
                </a>
            </div>
            <div class="block_12">
                <ul>
                    <li><a href="/">Главная</a></li>
                    <li><a href="">Курсы</a></li>
                    <li><a href="blog">Блог</a></li>
                    <li><a href="">О проекте</a></li>

                </ul>
            </div>
        </div>
    </div>