<?php include ROOT.'/views/layouts/header.phtml'?>
        <div class="block_1">
            <div class="header">
                <div class="block_25">
                    <div class="block_26">
                        <p>ВИДЕОКУРС ПРОГРАММИРОВАНИЯ</p>
                    </div>
                    <div class="block_27">
                        <p>НА ЯЗЫКЕ PHP</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="block_30">
            <div class="block_31">
                <h2>ЧТО ТАКОЕ PHP START?</h2>
                <p>Курс разработан специально для начинающих и учеников с неуверенными знаниями PHP.</br>
                    Буду с Вами честным: по его окончанию Вы не станете асом и матерым специалистом. Но гарантирую,</br>
                    что Вы освоите основы программирования, научитесь использовать PHP и получите хорошие шансы для трудоустройства.
                </p>
            </div>
            <div class="block_pic">
                <div class="block_pic1">
                    <img src="../../template/img/1.png">
                    <div class="block_pic1z">КАЧЕСТВЕННЫЕ ВИДЕОУРОКИ</div>
                    <div class="block_pic1t">Видео уже доступно: </br>
                        25 бесплатных теоретических</br>
                        и практических уроков общей </br>
                        продолжительностью около 14 часов
                    </div>
                </div>
                <div class="block_pic1">
                    <img src="../../template/img/2.png">
                    <div class="block_pic1z">УДОБНАЯ ПОДАЧА МАТЕРИАЛА</div>
                    <div class="block_pic1t">Программа курса хорошо продумана и </br>
                       структурирована. В каждом занятии </br>
                       Вы найдете описание, план </br>
                       и полезные ссылки
                    </div>
                </div>
                <div class="block_pic1">
                    <img src="../../template/img/4.png">
                    <div class="block_pic1z">ДОПОЛНИТЕЛЬНЫЕ МАТЕРИАЛЫ</div>
                    <div class="block_pic1t">Для самых упорных учеников, желающих </br>
                       стать php-ниндзя, я подготовил платные </br>
                        идополнительные материалы: домашние </br>
                       задания с решениями
                    </div>
                </div>
                <div class="block_pic1">
                    <img src="../../template/img/3.png">
                    <div class="block_pic1z">TELEGRAM-КАНАЛ О PHP</div>
                    <div class="block_pic1t">Прокачивайте знания в </br>
                    программировании получая информацию </br>
                    в нашем канале PHP Center</br>
                    продолжительностью около 14 часов
                    </div>
                </div>
            </div>
            <div class="bottom_block_30">
                <div class="bot_30z">ЧТО Я ОЖИДАЮ ОТ ВАС:</div>
                <div class="bot_30t">
                    Желание учиться</br>
                    Наличие свободного времени</br>
                    Умение работать с компьютером (файлами и папками, клавиатурой)</br>
                    Желательны начальные знания HTML и CSS (не обязательно!)
                </div>
            </div>
        </div>
    </body>
</html>

